import pytest
from src.chains.ingestion_chain import run_ingestion
from src.chains.query_chain import run_query
from src.storage.chroma import storage_client


def test_query_on_empty_corpus_refuses():
    # Ensure query on irrelevant query or non-existent document triggers structured refusal
    response = run_query(query="What is the speed of light in vacuum?", doc_id="non-existent-id")
    assert response.status == "refused"
    assert response.reason in ["insufficient_context", "low_relevance"]
    assert response.query == "What is the speed of light in vacuum?"


def test_query_flow_with_ingested_context(monkeypatch):
    # Ingest fixture
    content = (
        b"Solar panels convert sunlight into electrical energy using photovoltaic cells.\n"
        b"Inverters convert DC electricity generated by solar panels into AC electricity for household use."
    )
    ingested = run_ingestion(
        file_bytes=content,
        filename="solar_energy.txt",
        extension="txt",
    )
    doc_id = ingested["doc_id"]

    try:
        # Mock generator to avoid external network dependency in automated CI test
        from src.query.generator import AnswerWithCitations
        from src.query import generator

        # Find the chunk_id stored
        docs = storage_client.query(query_text="What do solar panels do?", k=1, filters={"doc_id": doc_id})
        assert len(docs) > 0
        target_chunk_id = docs[0].chunk_id

        def mock_generate(self, system_prompt, user_prompt, max_retries=3):
            return AnswerWithCitations(
                answer="Solar panels convert sunlight into electrical energy using photovoltaic cells.",
                citations=[target_chunk_id],
            )

        monkeypatch.setattr(generator.GroqGenerator, "generate", mock_generate)

        response = run_query(query="What do solar panels do?", doc_id=doc_id)
        assert response.status == "answered"
        assert "solar panels convert sunlight" in response.answer.lower()
        assert len(response.citations) >= 1
        assert response.citations[0].chunk_id == target_chunk_id
        assert response.citations[0].doc_name == "solar_energy.txt"

    finally:
        storage_client.delete_by_doc_id(doc_id)
