import json
import re
import time
from dataclasses import dataclass
from typing import AsyncGenerator, Protocol
from groq import Groq

from src.common.errors import GenerationError
from src.common.logging import StageTimer, logger
from src.config.settings import settings


@dataclass
class AnswerWithCitations:
    """Structured result generated by LLM."""
    answer: str
    citations: list[str]


class Generator(Protocol):
    """Protocol for pluggable LLM generation."""

    def generate(self, system_prompt: str, user_prompt: str) -> AnswerWithCitations:
        """Synchronously generate an answer with citations."""
        ...

    def generate_stream(self, system_prompt: str, user_prompt: str):
        """Stream generated answer tokens."""
        ...


def extract_json_payload(raw_text: str) -> dict:
    """Extract and parse JSON object from raw LLM text even if enclosed in markdown code fences."""
    raw_text = raw_text.strip()
    # Try direct parse
    try:
        return json.loads(raw_text)
    except json.JSONDecodeError:
        pass

    # Try extracting from markdown fence ```json ... ```
    match = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", raw_text, re.DOTALL)
    if match:
        try:
            return json.loads(match.group(1))
        except json.JSONDecodeError:
            pass

    # Try finding first { and last }
    first_brace = raw_text.find("{")
    last_brace = raw_text.rfind("}")
    if first_brace != -1 and last_brace != -1 and last_brace > first_brace:
        candidate = raw_text[first_brace : last_brace + 1]
        try:
            return json.loads(candidate)
        except json.JSONDecodeError:
            pass

    raise ValueError(f"Could not parse valid JSON from LLM output: {raw_text[:200]}")


class GroqGenerator:
    """Groq API LLM generation with retry and structured output parsing."""

    def __init__(
        self,
        api_key: str = settings.groq_api_key,
        model: str = settings.groq_model,
        temperature: float = settings.temperature,
    ):
        self.api_key = api_key
        self.model = model
        self.temperature = temperature
        self.client = Groq(api_key=self.api_key)

    def generate(
        self,
        system_prompt: str,
        user_prompt: str,
        max_retries: int = 3,
    ) -> AnswerWithCitations:
        last_error = None

        for attempt in range(1, max_retries + 1):
            try:
                with StageTimer("llm_generation", extra={"model": self.model, "attempt": attempt}):
                    response = self.client.chat.completions.create(
                        model=self.model,
                        temperature=self.temperature,
                        response_format={"type": "json_object"},
                        messages=[
                            {"role": "system", "content": system_prompt},
                            {"role": "user", "content": user_prompt},
                        ],
                    )
                    content = response.choices[0].message.content or ""
                    parsed = extract_json_payload(content)

                    answer = parsed.get("answer", "")
                    citations = parsed.get("citations", [])
                    if isinstance(citations, str):
                        citations = [citations]

                    return AnswerWithCitations(
                        answer=answer,
                        citations=citations,
                    )
            except Exception as e:
                last_error = e
                delay = 1.0 * (2 ** (attempt - 1))
                logger.warning(
                    f"Groq generation attempt {attempt}/{max_retries} failed: {e}. Retrying in {delay}s"
                )
                time.sleep(delay)

        logger.error(f"Groq generation failed after {max_retries} attempts: {last_error}")
        raise GenerationError(f"LLM generation failed: {last_error}") from last_error

    def generate_stream(self, system_prompt: str, user_prompt: str):
        """Streams tokens from Groq API."""
        try:
            stream = self.client.chat.completions.create(
                model=self.model,
                temperature=self.temperature,
                stream=True,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
            )
            for chunk in stream:
                delta = chunk.choices[0].delta.content
                if delta:
                    yield delta
        except Exception as e:
            logger.error(f"Streaming error from Groq: {e}")
            yield f"\n[Error streaming response: {e}]"


default_generator = GroqGenerator()
